# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTA5NmJiZTRkMDkyNDFlYWRjOWZiM2ZkMGY0N2NiZmUwMzYwMTVjYmVmNThkNGMzMjAxNzkxNGQyNzMxYjEyMTE5ODQ5MmQ4MTE1YzAwZTJkMzU1MmRjYzE1MDI5MTQ5ODY5MmE0MDFlMjBlMGQ5NTQ2NWIzMmRjMmVmMjk2NTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
